version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "pool_postgres"
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "54320:5432"
    volumes:
      - pool_db:/var/lib/postgresql/data
volumes:
  pool_db: