version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "pool_postgres"
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pool_db:/var/lib/postgresql/data
  prosper-pool:
    build: .
    environment:
      - LXRBITSIZE=30
    command: ["./wait-for-it.sh", "db:5432", "--", "private-pool", "--phost", "db", "--log", "debug" "--fhost", "http://172.17.0.1:8088"]
    volumes:
      - .:/go/src/prosper-pool
    ports:
      - "1234:1234"
      - "7070:7070"
    depends_on:
      - db
    links:
      - db
volumes:
  pool_db: