
[database]
  dbname = "postgres"
  host = "localhost"
  password = "password"
  port = 5432
  username = "postgres"

[factom]
  factomdlocation = "http://localhost:8088/v2"

[oracle]
  1forgekey = "CHANGME"
  apilayerkey = "CHANGME"
  coinmarketcapkey = "CHANGME"
  openexchangerateskey = "CHANGME"

[oracledatasources]
  1forge = -1
  alternativeme = -1
  apilayer = -1
  coincap = -1
  coinmarketcap = -1
  exchangerates = -1
  fixedusd = 0
  freeforexapi = -1
  kitco = -1
  openexchangerates = -1

[pegnet]
  pollingperiod = "2s"
  retryperiod = "5s"
